packages:
  - internal/*
  - common/*
  - apps/*
catalog:
  '@pnpm/workspace.read-manifest': ^1000.1.1
  '@types/archiver': ^6.0.3
  '@types/html-minifier-terser': ^7.0.2
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  dayjs: ^1.11.13
  dotenv: ^16.4.7
  rollup: ^4.35.0
  rollup-plugin-visualizer: ^5.14.0
  sass: ^1.85.1
  vite: ^6.2.1
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.3
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  '@jspm/generator': ^2.5.1
  archiver: ^7.0.1
  cheerio: ^1.0.0
  get-port: ^7.1.0
  html-minifier-terser: ^7.2.0
  nitropack: ^2.11.6
  resolve.exports: ^2.0.3
  vite-plugin-pwa: ^0.21.1
  vite-plugin-vue-devtools: ^7.7.2
  '@manypkg/get-packages': ^2.2.2
  chalk: ^5.4.1
  consola: ^3.4.0
  execa: ^9.5.2
  find-up: ^7.0.0
  ora: ^8.2.0
  pkg-types: ^1.3.1
  prettier: ^3.5.3
  rimraf: ^6.0.1
  vue: ^3.5.13
  unbuild: ^3.5.0
  turbo: ^2.4.4
